// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PawClinic.Persistence;

#nullable disable

namespace PawClinic.Persistence.Migrations
{
    [DbContext(typeof(PawClinicDbContext))]
    partial class PawClinicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("PawClinic.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonForVisit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VetId")
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.HasIndex("PetId");

                    b.HasIndex("VetId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = new Guid("d1000000-0000-0000-0000-000000000001"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Routine vaccination administered. All clear. Next visit in 12 months.",
                            PetId = new Guid("c1000000-0000-0000-0000-000000000001"),
                            ReasonForVisit = "Annual vaccination",
                            ScheduledDateTime = new DateTime(2025, 4, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            VetId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            AppointmentId = new Guid("d2000000-0000-0000-0000-000000000002"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Mild tartar build-up noted. Dental clean recommended in 6 months.",
                            PetId = new Guid("c2000000-0000-0000-0000-000000000002"),
                            ReasonForVisit = "Dental check-up",
                            ScheduledDateTime = new DateTime(2025, 5, 3, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            VetId = new Guid("a3000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            AppointmentId = new Guid("d3000000-0000-0000-0000-000000000003"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Owner cancelled — will reschedule.",
                            PetId = new Guid("c3000000-0000-0000-0000-000000000003"),
                            ReasonForVisit = "Weight check",
                            ScheduledDateTime = new DateTime(2025, 5, 20, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            VetId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            AppointmentId = new Guid("d4000000-0000-0000-0000-000000000004"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetId = new Guid("c1000000-0000-0000-0000-000000000001"),
                            ReasonForVisit = "Annual check-up",
                            ScheduledDateTime = new DateTime(2027, 6, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            VetId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            AppointmentId = new Guid("d5000000-0000-0000-0000-000000000005"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PetId = new Guid("c4000000-0000-0000-0000-000000000004"),
                            ReasonForVisit = "New patient consultation",
                            ScheduledDateTime = new DateTime(2027, 6, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            VetId = new Guid("a2000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("PawClinic.Domain.Entities.Owner", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            OwnerId = new Guid("b1000000-0000-0000-0000-000000000001"),
                            Address = "14 Elm Street, Springfield",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emily.johnson@example.com",
                            Name = "Mrs. Emily Johnson",
                            PhoneNumber = "555-0101"
                        },
                        new
                        {
                            OwnerId = new Guid("b2000000-0000-0000-0000-000000000002"),
                            Address = "7 Maple Avenue, Shelbyville",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pierre.dubois@example.com",
                            Name = "Mr. Pierre Dubois",
                            PhoneNumber = "555-0102"
                        },
                        new
                        {
                            OwnerId = new Guid("b3000000-0000-0000-0000-000000000003"),
                            Address = "23 Oak Lane, Capital City",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carmen.reyes@example.com",
                            Name = "Ms. Carmen Reyes",
                            PhoneNumber = "555-0103"
                        });
                });

            modelBuilder.Entity("PawClinic.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Breed")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Species")
                        .HasColumnType("INTEGER");

                    b.HasKey("PetId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            PetId = new Guid("c1000000-0000-0000-0000-000000000001"),
                            Breed = "Labrador Retriever",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            Name = "Bella",
                            OwnerId = new Guid("b1000000-0000-0000-0000-000000000001"),
                            Species = 0
                        },
                        new
                        {
                            PetId = new Guid("c2000000-0000-0000-0000-000000000002"),
                            Breed = "Maine Coon",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2020, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            Name = "Oscar",
                            OwnerId = new Guid("b2000000-0000-0000-0000-000000000002"),
                            Species = 1
                        },
                        new
                        {
                            PetId = new Guid("c3000000-0000-0000-0000-000000000003"),
                            Breed = "Holland Lop",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            Name = "Pip",
                            OwnerId = new Guid("b2000000-0000-0000-0000-000000000002"),
                            Species = 2
                        },
                        new
                        {
                            PetId = new Guid("c4000000-0000-0000-0000-000000000004"),
                            Breed = "Border Collie",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsArchived = false,
                            Name = "Luna",
                            OwnerId = new Guid("b3000000-0000-0000-0000-000000000003"),
                            Species = 0
                        });
                });

            modelBuilder.Entity("PawClinic.Domain.Entities.Vet", b =>
                {
                    b.Property<Guid>("VetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Specialisation")
                        .HasColumnType("INTEGER");

                    b.HasKey("VetId");

                    b.ToTable("Vets");

                    b.HasData(
                        new
                        {
                            VetId = new Guid("a1000000-0000-0000-0000-000000000001"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dr. Sarah Patel",
                            Specialisation = 0
                        },
                        new
                        {
                            VetId = new Guid("a2000000-0000-0000-0000-000000000002"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dr. James Okafor",
                            Specialisation = 1
                        },
                        new
                        {
                            VetId = new Guid("a3000000-0000-0000-0000-000000000003"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dr. Mei Lin",
                            Specialisation = 2
                        });
                });

            modelBuilder.Entity("PawClinic.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("PawClinic.Domain.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawClinic.Domain.Entities.Vet", "Vet")
                        .WithMany()
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Vet");
                });

            modelBuilder.Entity("PawClinic.Domain.Entities.Pet", b =>
                {
                    b.HasOne("PawClinic.Domain.Entities.Owner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PawClinic.Domain.Entities.Owner", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
